from PyQt5 import QtCore, QtGui, QtWidgets
import sys 
import json
import os

class Ui_MainWindow(object):
    IMAGE_PATH = "GeometricDescription.png"
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 953)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RunName_input = QtWidgets.QLineEdit(self.centralwidget)
        self.RunName_input.setGeometry(QtCore.QRect(10, 40, 113, 21))
        self.RunName_input.setText("")
        self.RunName_input.setObjectName("RunName_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 60, 16))
        self.label.setObjectName("label")
        self.StartDate_input = QtWidgets.QLineEdit(self.centralwidget)
        self.StartDate_input.setGeometry(QtCore.QRect(10, 90, 113, 21))
        self.StartDate_input.setObjectName("StartDate_input")
        self.EndDate_input = QtWidgets.QLineEdit(self.centralwidget)
        self.EndDate_input.setGeometry(QtCore.QRect(10, 140, 113, 21))
        self.EndDate_input.setObjectName("EndDate_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 30, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 70, 60, 16))
        self.label_5.setObjectName("label_5")
        self.FPGASN_ipt_01 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_01.setGeometry(QtCore.QRect(350, 30, 51, 21))
        self.FPGASN_ipt_01.setObjectName("FPGASN_ipt_01")
        self.MTBSN_ipt_01 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_01.setGeometry(QtCore.QRect(350, 70, 51, 21))
        self.MTBSN_ipt_01.setObjectName("MTBSN_ipt_01")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 10, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(420, 10, 60, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(560, 10, 60, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(490, 10, 60, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(630, 10, 60, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(700, 10, 60, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(770, 10, 60, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(840, 10, 60, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(290, 160, 60, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(630, 100, 60, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(490, 100, 60, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(420, 100, 60, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(290, 120, 60, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(770, 100, 60, 16))
        self.label_19.setObjectName("label_19")
        self.FPGASN_ipt_09 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_09.setGeometry(QtCore.QRect(350, 120, 51, 21))
        self.FPGASN_ipt_09.setObjectName("FPGASN_ipt_09")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(560, 100, 60, 16))
        self.label_20.setObjectName("label_20")
        self.MTBSN_ipt_09 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_09.setGeometry(QtCore.QRect(350, 160, 51, 21))
        self.MTBSN_ipt_09.setObjectName("MTBSN_ipt_09")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(700, 100, 60, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(840, 100, 60, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(350, 100, 60, 16))
        self.label_23.setObjectName("label_23")
        self.FPGASN_ipt_03 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_03.setGeometry(QtCore.QRect(490, 30, 51, 21))
        self.FPGASN_ipt_03.setObjectName("FPGASN_ipt_03")
        self.MTBSN_ipt_03 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_03.setGeometry(QtCore.QRect(490, 70, 51, 21))
        self.MTBSN_ipt_03.setObjectName("MTBSN_ipt_03")
        self.MTBSN_ipt_02 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_02.setGeometry(QtCore.QRect(420, 70, 51, 21))
        self.MTBSN_ipt_02.setObjectName("MTBSN_ipt_02")
        self.FPGASN_ipt_04 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_04.setGeometry(QtCore.QRect(560, 30, 51, 21))
        self.FPGASN_ipt_04.setObjectName("FPGASN_ipt_04")
        self.FPGASN_ipt_05 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_05.setGeometry(QtCore.QRect(630, 30, 51, 21))
        self.FPGASN_ipt_05.setObjectName("FPGASN_ipt_05")
        self.FPGASN_ipt_06 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_06.setGeometry(QtCore.QRect(700, 30, 51, 21))
        self.FPGASN_ipt_06.setObjectName("FPGASN_ipt_06")
        self.MTBSN_ipt_05 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_05.setGeometry(QtCore.QRect(630, 70, 51, 21))
        self.MTBSN_ipt_05.setObjectName("MTBSN_ipt_05")
        self.MTBSN_ipt_04 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_04.setGeometry(QtCore.QRect(560, 70, 51, 21))
        self.MTBSN_ipt_04.setObjectName("MTBSN_ipt_04")
        self.FPGASN_ipt_02 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_02.setGeometry(QtCore.QRect(420, 30, 51, 21))
        self.FPGASN_ipt_02.setObjectName("FPGASN_ipt_02")
        self.FPGASN_ipt_07 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_07.setGeometry(QtCore.QRect(770, 30, 51, 21))
        self.FPGASN_ipt_07.setObjectName("FPGASN_ipt_07")
        self.MTBSN_ipt_07 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_07.setGeometry(QtCore.QRect(770, 70, 51, 21))
        self.MTBSN_ipt_07.setObjectName("MTBSN_ipt_07")
        self.FPGASN_ipt_08 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_08.setGeometry(QtCore.QRect(840, 30, 51, 21))
        self.FPGASN_ipt_08.setObjectName("FPGASN_ipt_08")
        self.MTBSN_ipt_08 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_08.setGeometry(QtCore.QRect(840, 70, 51, 21))
        self.MTBSN_ipt_08.setObjectName("MTBSN_ipt_08")
        self.FPGASN_ipt_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_11.setGeometry(QtCore.QRect(490, 120, 51, 21))
        self.FPGASN_ipt_11.setObjectName("FPGASN_ipt_11")
        self.FPGASN_ipt_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_10.setGeometry(QtCore.QRect(420, 120, 51, 21))
        self.FPGASN_ipt_10.setObjectName("FPGASN_ipt_10")
        self.MTBSN_ipt_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_10.setGeometry(QtCore.QRect(420, 160, 51, 21))
        self.MTBSN_ipt_10.setObjectName("MTBSN_ipt_10")
        self.MTBSN_ipt_06 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_06.setGeometry(QtCore.QRect(700, 70, 51, 21))
        self.MTBSN_ipt_06.setObjectName("MTBSN_ipt_06")
        self.FPGASN_ipt_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_13.setGeometry(QtCore.QRect(630, 120, 51, 21))
        self.FPGASN_ipt_13.setObjectName("FPGASN_ipt_13")
        self.FPGASN_ipt_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_12.setGeometry(QtCore.QRect(560, 120, 51, 21))
        self.FPGASN_ipt_12.setObjectName("FPGASN_ipt_12")
        self.MTBSN_ipt_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_13.setGeometry(QtCore.QRect(630, 160, 51, 21))
        self.MTBSN_ipt_13.setObjectName("MTBSN_ipt_13")
        self.MTBSN_ipt_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_12.setGeometry(QtCore.QRect(560, 160, 51, 21))
        self.MTBSN_ipt_12.setObjectName("MTBSN_ipt_12")
        self.MTBSN_ipt_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_11.setGeometry(QtCore.QRect(490, 160, 51, 21))
        self.MTBSN_ipt_11.setObjectName("MTBSN_ipt_11")
        self.FPGASN_ipt_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_15.setGeometry(QtCore.QRect(770, 120, 51, 21))
        self.FPGASN_ipt_15.setObjectName("FPGASN_ipt_15")
        self.MTBSN_ipt_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_15.setGeometry(QtCore.QRect(770, 160, 51, 21))
        self.MTBSN_ipt_15.setObjectName("MTBSN_ipt_15")
        self.MTBSN_ipt_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_14.setGeometry(QtCore.QRect(700, 160, 51, 21))
        self.MTBSN_ipt_14.setObjectName("MTBSN_ipt_14")
        self.FPGASN_ipt_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_16.setGeometry(QtCore.QRect(840, 120, 51, 21))
        self.FPGASN_ipt_16.setObjectName("FPGASN_ipt_16")
        self.MTBSN_ipt_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.MTBSN_ipt_16.setGeometry(QtCore.QRect(840, 160, 51, 21))
        self.MTBSN_ipt_16.setObjectName("MTBSN_ipt_16")
        self.FPGASN_ipt_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.FPGASN_ipt_14.setGeometry(QtCore.QRect(700, 120, 51, 21))
        self.FPGASN_ipt_14.setObjectName("FPGASN_ipt_14")


        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(920, 20, 251, 171))
        self.graphicsView.setObjectName("graphicsView")
        # 圖片載入邏輯（僅顯示縮略圖）
        img = QtGui.QPixmap(self.IMAGE_PATH)
        scene = QtWidgets.QGraphicsScene()
        if not img.isNull():
            view_size = self.graphicsView.size()
            scaled_img = img.scaled(view_size, 
                                    QtCore.Qt.KeepAspectRatio, 
                                    QtCore.Qt.SmoothTransformation)
            scene.addPixmap(scaled_img)
        self.graphicsView.setScene(scene)

        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(10, 190, 71, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(10, 210, 71, 16))
        self.label_25.setObjectName("label_25")
        self.B1_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_0.setGeometry(QtCore.QRect(30, 320, 81, 21))
        self.B1_CID_0.setObjectName("B1_CID_0")
        self.B1_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_1.setGeometry(QtCore.QRect(120, 320, 81, 21))
        self.B1_CID_1.setObjectName("B1_CID_1")
        self.B1_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_2.setGeometry(QtCore.QRect(210, 320, 81, 21))
        self.B1_CID_2.setObjectName("B1_CID_2")
        self.B1_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_3.setGeometry(QtCore.QRect(300, 320, 81, 21))
        self.B1_CID_3.setObjectName("B1_CID_3")
        self.B1_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_4.setGeometry(QtCore.QRect(30, 290, 81, 21))
        self.B1_CID_4.setObjectName("B1_CID_4")
        self.B1_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_5.setGeometry(QtCore.QRect(120, 290, 81, 21))
        self.B1_CID_5.setObjectName("B1_CID_5")
        self.B1_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_6.setGeometry(QtCore.QRect(210, 290, 81, 21))
        self.B1_CID_6.setObjectName("B1_CID_6")
        self.B1_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_7.setGeometry(QtCore.QRect(300, 290, 81, 21))
        self.B1_CID_7.setObjectName("B1_CID_7")
        self.B1_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_8.setGeometry(QtCore.QRect(30, 260, 81, 21))
        self.B1_CID_8.setObjectName("B1_CID_8")
        self.B1_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_9.setGeometry(QtCore.QRect(120, 260, 81, 21))
        self.B1_CID_9.setObjectName("B1_CID_9")
        self.B1_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_10.setGeometry(QtCore.QRect(210, 260, 81, 21))
        self.B1_CID_10.setObjectName("B1_CID_10")
        self.B1_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_11.setGeometry(QtCore.QRect(300, 260, 81, 21))
        self.B1_CID_11.setObjectName("B1_CID_11")
        self.B1_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_12.setGeometry(QtCore.QRect(30, 230, 81, 21))
        self.B1_CID_12.setText("")
        self.B1_CID_12.setObjectName("B1_CID_12")
        self.B1_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_13.setGeometry(QtCore.QRect(120, 230, 81, 21))
        self.B1_CID_13.setObjectName("B1_CID_13")
        self.B1_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_14.setGeometry(QtCore.QRect(210, 230, 81, 21))
        self.B1_CID_14.setObjectName("B1_CID_14")
        self.B1_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B1_CID_15.setGeometry(QtCore.QRect(300, 230, 81, 21))
        self.B1_CID_15.setObjectName("B1_CID_15")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(390, 210, 71, 16))
        self.label_26.setObjectName("label_26")
        self.B2_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_4.setGeometry(QtCore.QRect(410, 290, 81, 21))
        self.B2_CID_4.setObjectName("B2_CID_4")
        self.B2_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_6.setGeometry(QtCore.QRect(590, 290, 81, 21))
        self.B2_CID_6.setObjectName("B2_CID_6")
        self.B2_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_12.setGeometry(QtCore.QRect(410, 230, 81, 21))
        self.B2_CID_12.setObjectName("B2_CID_12")
        self.B2_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_8.setGeometry(QtCore.QRect(410, 260, 81, 21))
        self.B2_CID_8.setObjectName("B2_CID_8")
        self.B2_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_2.setGeometry(QtCore.QRect(590, 320, 81, 21))
        self.B2_CID_2.setObjectName("B2_CID_2")
        self.B2_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_5.setGeometry(QtCore.QRect(500, 290, 81, 21))
        self.B2_CID_5.setObjectName("B2_CID_5")
        self.B2_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_13.setGeometry(QtCore.QRect(500, 230, 81, 21))
        self.B2_CID_13.setObjectName("B2_CID_13")
        self.B2_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_9.setGeometry(QtCore.QRect(500, 260, 81, 21))
        self.B2_CID_9.setObjectName("B2_CID_9")
        self.B2_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_14.setGeometry(QtCore.QRect(590, 230, 81, 21))
        self.B2_CID_14.setObjectName("B2_CID_14")
        self.B2_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_0.setGeometry(QtCore.QRect(410, 320, 81, 21))
        self.B2_CID_0.setObjectName("B2_CID_0")
        self.B2_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_3.setGeometry(QtCore.QRect(680, 320, 81, 21))
        self.B2_CID_3.setObjectName("B2_CID_3")
        self.B2_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_10.setGeometry(QtCore.QRect(590, 260, 81, 21))
        self.B2_CID_10.setObjectName("B2_CID_10")
        self.B2_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_7.setGeometry(QtCore.QRect(680, 290, 81, 21))
        self.B2_CID_7.setObjectName("B2_CID_7")
        self.B2_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_15.setGeometry(QtCore.QRect(680, 230, 81, 21))
        self.B2_CID_15.setObjectName("B2_CID_15")
        self.B2_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_1.setGeometry(QtCore.QRect(500, 320, 81, 21))
        self.B2_CID_1.setObjectName("B2_CID_1")
        self.B2_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B2_CID_11.setGeometry(QtCore.QRect(680, 260, 81, 21))
        self.B2_CID_11.setObjectName("B2_CID_11")
        self.B3_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_4.setGeometry(QtCore.QRect(790, 290, 81, 21))
        self.B3_CID_4.setObjectName("B3_CID_4")
        self.B4_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_0.setGeometry(QtCore.QRect(1170, 320, 81, 21))
        self.B4_CID_0.setObjectName("B4_CID_0")
        self.B4_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_11.setGeometry(QtCore.QRect(1440, 260, 81, 21))
        self.B4_CID_11.setObjectName("B4_CID_11")
        self.B3_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_3.setGeometry(QtCore.QRect(1060, 320, 81, 21))
        self.B3_CID_3.setObjectName("B3_CID_3")
        self.B4_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_1.setGeometry(QtCore.QRect(1260, 320, 81, 21))
        self.B4_CID_1.setObjectName("B4_CID_1")
        self.B3_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_5.setGeometry(QtCore.QRect(880, 290, 81, 21))
        self.B3_CID_5.setObjectName("B3_CID_5")
        self.B4_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_2.setGeometry(QtCore.QRect(1350, 320, 81, 21))
        self.B4_CID_2.setObjectName("B4_CID_2")
        self.B4_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_8.setGeometry(QtCore.QRect(1170, 260, 81, 21))
        self.B4_CID_8.setObjectName("B4_CID_8")
        self.B3_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_2.setGeometry(QtCore.QRect(970, 320, 81, 21))
        self.B3_CID_2.setObjectName("B3_CID_2")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(1150, 210, 71, 16))
        self.label_27.setObjectName("label_27")
        self.B4_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_13.setGeometry(QtCore.QRect(1260, 230, 81, 21))
        self.B4_CID_13.setObjectName("B4_CID_13")
        self.B3_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_6.setGeometry(QtCore.QRect(970, 290, 81, 21))
        self.B3_CID_6.setObjectName("B3_CID_6")
        self.B3_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_14.setGeometry(QtCore.QRect(970, 230, 81, 21))
        self.B3_CID_14.setObjectName("B3_CID_14")
        self.B4_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_5.setGeometry(QtCore.QRect(1260, 290, 81, 21))
        self.B4_CID_5.setObjectName("B4_CID_5")
        self.B3_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_11.setGeometry(QtCore.QRect(1060, 260, 81, 21))
        self.B3_CID_11.setObjectName("B3_CID_11")
        self.B4_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_9.setGeometry(QtCore.QRect(1260, 260, 81, 21))
        self.B4_CID_9.setObjectName("B4_CID_9")
        self.B3_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_12.setGeometry(QtCore.QRect(790, 230, 81, 21))
        self.B3_CID_12.setText("")
        self.B3_CID_12.setObjectName("B3_CID_12")
        self.B4_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_6.setGeometry(QtCore.QRect(1350, 290, 81, 21))
        self.B4_CID_6.setObjectName("B4_CID_6")
        self.B3_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_9.setGeometry(QtCore.QRect(880, 260, 81, 21))
        self.B3_CID_9.setObjectName("B3_CID_9")
        self.B4_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_12.setGeometry(QtCore.QRect(1170, 230, 81, 21))
        self.B4_CID_12.setObjectName("B4_CID_12")
        self.B4_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_14.setGeometry(QtCore.QRect(1350, 230, 81, 21))
        self.B4_CID_14.setObjectName("B4_CID_14")
        self.B4_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_7.setGeometry(QtCore.QRect(1440, 290, 81, 21))
        self.B4_CID_7.setObjectName("B4_CID_7")
        self.B4_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_3.setGeometry(QtCore.QRect(1440, 320, 81, 21))
        self.B4_CID_3.setObjectName("B4_CID_3")
        self.B3_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_1.setGeometry(QtCore.QRect(880, 320, 81, 21))
        self.B3_CID_1.setObjectName("B3_CID_1")
        self.B4_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_4.setGeometry(QtCore.QRect(1170, 290, 81, 21))
        self.B4_CID_4.setObjectName("B4_CID_4")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(770, 210, 71, 16))
        self.label_29.setObjectName("label_29")
        self.B3_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_7.setGeometry(QtCore.QRect(1060, 290, 81, 21))
        self.B3_CID_7.setObjectName("B3_CID_7")
        self.B3_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_15.setGeometry(QtCore.QRect(1060, 230, 81, 21))
        self.B3_CID_15.setObjectName("B3_CID_15")
        self.B4_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_10.setGeometry(QtCore.QRect(1350, 260, 81, 21))
        self.B4_CID_10.setObjectName("B4_CID_10")
        self.B3_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_0.setGeometry(QtCore.QRect(790, 320, 81, 21))
        self.B3_CID_0.setObjectName("B3_CID_0")
        self.B3_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_13.setGeometry(QtCore.QRect(880, 230, 81, 21))
        self.B3_CID_13.setObjectName("B3_CID_13")
        self.B4_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B4_CID_15.setGeometry(QtCore.QRect(1440, 230, 81, 21))
        self.B4_CID_15.setObjectName("B4_CID_15")
        self.B3_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_8.setGeometry(QtCore.QRect(790, 260, 81, 21))
        self.B3_CID_8.setObjectName("B3_CID_8")
        self.B3_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B3_CID_10.setGeometry(QtCore.QRect(970, 260, 81, 21))
        self.B3_CID_10.setObjectName("B3_CID_10")
        self.B7_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_0.setGeometry(QtCore.QRect(790, 460, 81, 21))
        self.B7_CID_0.setObjectName("B7_CID_0")
        self.B6_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_7.setGeometry(QtCore.QRect(680, 430, 81, 21))
        self.B6_CID_7.setObjectName("B6_CID_7")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(390, 350, 71, 16))
        self.label_28.setObjectName("label_28")
        self.B6_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_4.setGeometry(QtCore.QRect(410, 430, 81, 21))
        self.B6_CID_4.setObjectName("B6_CID_4")
        self.B7_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_3.setGeometry(QtCore.QRect(1060, 460, 81, 21))
        self.B7_CID_3.setObjectName("B7_CID_3")
        self.B6_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_13.setGeometry(QtCore.QRect(500, 370, 81, 21))
        self.B6_CID_13.setObjectName("B6_CID_13")
        self.B8_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_15.setGeometry(QtCore.QRect(1440, 370, 81, 21))
        self.B8_CID_15.setObjectName("B8_CID_15")
        self.B5_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_2.setGeometry(QtCore.QRect(210, 460, 81, 21))
        self.B5_CID_2.setObjectName("B5_CID_2")
        self.B7_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_14.setGeometry(QtCore.QRect(970, 370, 81, 21))
        self.B7_CID_14.setObjectName("B7_CID_14")
        self.B8_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_2.setGeometry(QtCore.QRect(1350, 460, 81, 21))
        self.B8_CID_2.setObjectName("B8_CID_2")
        self.B8_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_12.setGeometry(QtCore.QRect(1170, 370, 81, 21))
        self.B8_CID_12.setObjectName("B8_CID_12")
        self.B8_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_11.setGeometry(QtCore.QRect(1440, 400, 81, 21))
        self.B8_CID_11.setObjectName("B8_CID_11")
        self.B7_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_5.setGeometry(QtCore.QRect(880, 430, 81, 21))
        self.B7_CID_5.setObjectName("B7_CID_5")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(770, 350, 71, 16))
        self.label_30.setObjectName("label_30")
        self.B7_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_13.setGeometry(QtCore.QRect(880, 370, 81, 21))
        self.B7_CID_13.setObjectName("B7_CID_13")
        self.B6_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_15.setGeometry(QtCore.QRect(680, 370, 81, 21))
        self.B6_CID_15.setObjectName("B6_CID_15")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(10, 350, 71, 16))
        self.label_31.setObjectName("label_31")
        self.B7_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_9.setGeometry(QtCore.QRect(880, 400, 81, 21))
        self.B7_CID_9.setObjectName("B7_CID_9")
        self.B6_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_5.setGeometry(QtCore.QRect(500, 430, 81, 21))
        self.B6_CID_5.setObjectName("B6_CID_5")
        self.B6_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_14.setGeometry(QtCore.QRect(590, 370, 81, 21))
        self.B6_CID_14.setObjectName("B6_CID_14")
        self.B5_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_6.setGeometry(QtCore.QRect(210, 430, 81, 21))
        self.B5_CID_6.setObjectName("B5_CID_6")
        self.B6_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_0.setGeometry(QtCore.QRect(410, 460, 81, 21))
        self.B6_CID_0.setObjectName("B6_CID_0")
        self.B5_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_15.setGeometry(QtCore.QRect(300, 370, 81, 21))
        self.B5_CID_15.setObjectName("B5_CID_15")
        self.B7_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_8.setGeometry(QtCore.QRect(790, 400, 81, 21))
        self.B7_CID_8.setObjectName("B7_CID_8")
        self.B6_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_10.setGeometry(QtCore.QRect(590, 400, 81, 21))
        self.B6_CID_10.setObjectName("B6_CID_10")
        self.B6_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_11.setGeometry(QtCore.QRect(680, 400, 81, 21))
        self.B6_CID_11.setObjectName("B6_CID_11")
        self.B8_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_4.setGeometry(QtCore.QRect(1170, 430, 81, 21))
        self.B8_CID_4.setObjectName("B8_CID_4")
        self.B6_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_3.setGeometry(QtCore.QRect(680, 460, 81, 21))
        self.B6_CID_3.setObjectName("B6_CID_3")
        self.B8_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_1.setGeometry(QtCore.QRect(1260, 460, 81, 21))
        self.B8_CID_1.setObjectName("B8_CID_1")
        self.B5_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_12.setGeometry(QtCore.QRect(30, 370, 81, 21))
        self.B5_CID_12.setText("")
        self.B5_CID_12.setObjectName("B5_CID_12")
        self.B8_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_14.setGeometry(QtCore.QRect(1350, 370, 81, 21))
        self.B8_CID_14.setObjectName("B8_CID_14")
        self.B5_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_13.setGeometry(QtCore.QRect(120, 370, 81, 21))
        self.B5_CID_13.setObjectName("B5_CID_13")
        self.B7_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_2.setGeometry(QtCore.QRect(970, 460, 81, 21))
        self.B7_CID_2.setObjectName("B7_CID_2")
        self.B8_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_10.setGeometry(QtCore.QRect(1350, 400, 81, 21))
        self.B8_CID_10.setObjectName("B8_CID_10")
        self.B7_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_11.setGeometry(QtCore.QRect(1060, 400, 81, 21))
        self.B7_CID_11.setObjectName("B7_CID_11")
        self.B5_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_14.setGeometry(QtCore.QRect(210, 370, 81, 21))
        self.B5_CID_14.setObjectName("B5_CID_14")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(1150, 350, 71, 16))
        self.label_32.setObjectName("label_32")
        self.B8_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_9.setGeometry(QtCore.QRect(1260, 400, 81, 21))
        self.B8_CID_9.setObjectName("B8_CID_9")
        self.B6_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_1.setGeometry(QtCore.QRect(500, 460, 81, 21))
        self.B6_CID_1.setObjectName("B6_CID_1")
        self.B5_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_8.setGeometry(QtCore.QRect(30, 400, 81, 21))
        self.B5_CID_8.setObjectName("B5_CID_8")
        self.B8_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_7.setGeometry(QtCore.QRect(1440, 430, 81, 21))
        self.B8_CID_7.setObjectName("B8_CID_7")
        self.B8_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_3.setGeometry(QtCore.QRect(1440, 460, 81, 21))
        self.B8_CID_3.setObjectName("B8_CID_3")
        self.B7_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_4.setGeometry(QtCore.QRect(790, 430, 81, 21))
        self.B7_CID_4.setObjectName("B7_CID_4")
        self.B8_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_5.setGeometry(QtCore.QRect(1260, 430, 81, 21))
        self.B8_CID_5.setObjectName("B8_CID_5")
        self.B7_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_7.setGeometry(QtCore.QRect(1060, 430, 81, 21))
        self.B7_CID_7.setObjectName("B7_CID_7")
        self.B5_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_7.setGeometry(QtCore.QRect(300, 430, 81, 21))
        self.B5_CID_7.setObjectName("B5_CID_7")
        self.B5_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_0.setGeometry(QtCore.QRect(30, 460, 81, 21))
        self.B5_CID_0.setObjectName("B5_CID_0")
        self.B5_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_3.setGeometry(QtCore.QRect(300, 460, 81, 21))
        self.B5_CID_3.setObjectName("B5_CID_3")
        self.B7_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_10.setGeometry(QtCore.QRect(970, 400, 81, 21))
        self.B7_CID_10.setObjectName("B7_CID_10")
        self.B6_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_8.setGeometry(QtCore.QRect(410, 400, 81, 21))
        self.B6_CID_8.setObjectName("B6_CID_8")
        self.B7_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_12.setGeometry(QtCore.QRect(790, 370, 81, 21))
        self.B7_CID_12.setText("")
        self.B7_CID_12.setObjectName("B7_CID_12")
        self.B8_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_0.setGeometry(QtCore.QRect(1170, 460, 81, 21))
        self.B8_CID_0.setObjectName("B8_CID_0")
        self.B6_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_12.setGeometry(QtCore.QRect(410, 370, 81, 21))
        self.B6_CID_12.setObjectName("B6_CID_12")
        self.B5_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_1.setGeometry(QtCore.QRect(120, 460, 81, 21))
        self.B5_CID_1.setObjectName("B5_CID_1")
        self.B8_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_8.setGeometry(QtCore.QRect(1170, 400, 81, 21))
        self.B8_CID_8.setObjectName("B8_CID_8")
        self.B6_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_9.setGeometry(QtCore.QRect(500, 400, 81, 21))
        self.B6_CID_9.setObjectName("B6_CID_9")
        self.B7_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_6.setGeometry(QtCore.QRect(970, 430, 81, 21))
        self.B7_CID_6.setObjectName("B7_CID_6")
        self.B7_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_15.setGeometry(QtCore.QRect(1060, 370, 81, 21))
        self.B7_CID_15.setObjectName("B7_CID_15")
        self.B8_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_13.setGeometry(QtCore.QRect(1260, 370, 81, 21))
        self.B8_CID_13.setObjectName("B8_CID_13")
        self.B7_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B7_CID_1.setGeometry(QtCore.QRect(880, 460, 81, 21))
        self.B7_CID_1.setObjectName("B7_CID_1")
        self.B6_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_2.setGeometry(QtCore.QRect(590, 460, 81, 21))
        self.B6_CID_2.setObjectName("B6_CID_2")
        self.B5_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_9.setGeometry(QtCore.QRect(120, 400, 81, 21))
        self.B5_CID_9.setObjectName("B5_CID_9")
        self.B8_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B8_CID_6.setGeometry(QtCore.QRect(1350, 430, 81, 21))
        self.B8_CID_6.setObjectName("B8_CID_6")
        self.B5_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_10.setGeometry(QtCore.QRect(210, 400, 81, 21))
        self.B5_CID_10.setObjectName("B5_CID_10")
        self.B5_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_11.setGeometry(QtCore.QRect(300, 400, 81, 21))
        self.B5_CID_11.setObjectName("B5_CID_11")
        self.B5_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_4.setGeometry(QtCore.QRect(30, 430, 81, 21))
        self.B5_CID_4.setObjectName("B5_CID_4")
        self.B5_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B5_CID_5.setGeometry(QtCore.QRect(120, 430, 81, 21))
        self.B5_CID_5.setObjectName("B5_CID_5")
        self.B6_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B6_CID_6.setGeometry(QtCore.QRect(590, 430, 81, 21))
        self.B6_CID_6.setObjectName("B6_CID_6")
        self.B11_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_6.setGeometry(QtCore.QRect(970, 560, 81, 21))
        self.B11_CID_6.setObjectName("B11_CID_6")
        self.B9_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_12.setGeometry(QtCore.QRect(30, 500, 81, 21))
        self.B9_CID_12.setText("")
        self.B9_CID_12.setObjectName("B9_CID_12")
        self.B11_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_15.setGeometry(QtCore.QRect(1060, 500, 81, 21))
        self.B11_CID_15.setObjectName("B11_CID_15")
        self.B11_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_4.setGeometry(QtCore.QRect(790, 560, 81, 21))
        self.B11_CID_4.setObjectName("B11_CID_4")
        self.B10_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_12.setGeometry(QtCore.QRect(410, 500, 81, 21))
        self.B10_CID_12.setObjectName("B10_CID_12")
        self.B10_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_11.setGeometry(QtCore.QRect(680, 530, 81, 21))
        self.B10_CID_11.setObjectName("B10_CID_11")
        self.B10_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_9.setGeometry(QtCore.QRect(500, 530, 81, 21))
        self.B10_CID_9.setObjectName("B10_CID_9")
        self.B10_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_14.setGeometry(QtCore.QRect(590, 500, 81, 21))
        self.B10_CID_14.setObjectName("B10_CID_14")
        self.B11_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_14.setGeometry(QtCore.QRect(970, 500, 81, 21))
        self.B11_CID_14.setObjectName("B11_CID_14")
        self.B9_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_7.setGeometry(QtCore.QRect(300, 560, 81, 21))
        self.B9_CID_7.setObjectName("B9_CID_7")
        self.B12_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_6.setGeometry(QtCore.QRect(1350, 560, 81, 21))
        self.B12_CID_6.setObjectName("B12_CID_6")
        self.B9_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_0.setGeometry(QtCore.QRect(30, 590, 81, 21))
        self.B9_CID_0.setObjectName("B9_CID_0")
        self.B12_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_1.setGeometry(QtCore.QRect(1260, 590, 81, 21))
        self.B12_CID_1.setObjectName("B12_CID_1")
        self.B12_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_4.setGeometry(QtCore.QRect(1170, 560, 81, 21))
        self.B12_CID_4.setObjectName("B12_CID_4")
        self.B11_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_11.setGeometry(QtCore.QRect(1060, 530, 81, 21))
        self.B11_CID_11.setObjectName("B11_CID_11")
        self.B9_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_1.setGeometry(QtCore.QRect(120, 590, 81, 21))
        self.B9_CID_1.setObjectName("B9_CID_1")
        self.B10_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_6.setGeometry(QtCore.QRect(590, 560, 81, 21))
        self.B10_CID_6.setObjectName("B10_CID_6")
        self.B10_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_4.setGeometry(QtCore.QRect(410, 560, 81, 21))
        self.B10_CID_4.setObjectName("B10_CID_4")
        self.B10_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_10.setGeometry(QtCore.QRect(590, 530, 81, 21))
        self.B10_CID_10.setObjectName("B10_CID_10")
        self.B9_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_5.setGeometry(QtCore.QRect(120, 560, 81, 21))
        self.B9_CID_5.setObjectName("B9_CID_5")
        self.B12_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_15.setGeometry(QtCore.QRect(1440, 500, 81, 21))
        self.B12_CID_15.setObjectName("B12_CID_15")
        self.B9_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_2.setGeometry(QtCore.QRect(210, 590, 81, 21))
        self.B9_CID_2.setObjectName("B9_CID_2")
        self.B10_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_3.setGeometry(QtCore.QRect(680, 590, 81, 21))
        self.B10_CID_3.setObjectName("B10_CID_3")
        self.B10_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_2.setGeometry(QtCore.QRect(590, 590, 81, 21))
        self.B10_CID_2.setObjectName("B10_CID_2")
        self.B12_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_0.setGeometry(QtCore.QRect(1170, 590, 81, 21))
        self.B12_CID_0.setObjectName("B12_CID_0")
        self.B11_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_9.setGeometry(QtCore.QRect(880, 530, 81, 21))
        self.B11_CID_9.setObjectName("B11_CID_9")
        self.B11_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_5.setGeometry(QtCore.QRect(880, 560, 81, 21))
        self.B11_CID_5.setObjectName("B11_CID_5")
        self.B12_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_7.setGeometry(QtCore.QRect(1440, 560, 81, 21))
        self.B12_CID_7.setObjectName("B12_CID_7")
        self.B11_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_1.setGeometry(QtCore.QRect(880, 590, 81, 21))
        self.B11_CID_1.setObjectName("B11_CID_1")
        self.B11_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_12.setGeometry(QtCore.QRect(790, 500, 81, 21))
        self.B11_CID_12.setText("")
        self.B11_CID_12.setObjectName("B11_CID_12")
        self.B9_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_6.setGeometry(QtCore.QRect(210, 560, 81, 21))
        self.B9_CID_6.setObjectName("B9_CID_6")
        self.B11_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_3.setGeometry(QtCore.QRect(1060, 590, 81, 21))
        self.B11_CID_3.setObjectName("B11_CID_3")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(10, 480, 71, 16))
        self.label_33.setObjectName("label_33")
        self.B11_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_0.setGeometry(QtCore.QRect(790, 590, 81, 21))
        self.B11_CID_0.setObjectName("B11_CID_0")
        self.B12_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_3.setGeometry(QtCore.QRect(1440, 590, 81, 21))
        self.B12_CID_3.setObjectName("B12_CID_3")
        self.B10_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_1.setGeometry(QtCore.QRect(500, 590, 81, 21))
        self.B10_CID_1.setObjectName("B10_CID_1")
        self.B11_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_10.setGeometry(QtCore.QRect(970, 530, 81, 21))
        self.B11_CID_10.setObjectName("B11_CID_10")
        self.B9_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_14.setGeometry(QtCore.QRect(210, 500, 81, 21))
        self.B9_CID_14.setObjectName("B9_CID_14")
        self.B10_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_5.setGeometry(QtCore.QRect(500, 560, 81, 21))
        self.B10_CID_5.setObjectName("B10_CID_5")
        self.B12_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_11.setGeometry(QtCore.QRect(1440, 530, 81, 21))
        self.B12_CID_11.setObjectName("B12_CID_11")
        self.B10_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_8.setGeometry(QtCore.QRect(410, 530, 81, 21))
        self.B10_CID_8.setObjectName("B10_CID_8")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(390, 480, 71, 16))
        self.label_34.setObjectName("label_34")
        self.B10_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_7.setGeometry(QtCore.QRect(680, 560, 81, 21))
        self.B10_CID_7.setObjectName("B10_CID_7")
        self.B9_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_13.setGeometry(QtCore.QRect(120, 500, 81, 21))
        self.B9_CID_13.setObjectName("B9_CID_13")
        self.B9_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_15.setGeometry(QtCore.QRect(300, 500, 81, 21))
        self.B9_CID_15.setObjectName("B9_CID_15")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(1150, 480, 71, 16))
        self.label_35.setObjectName("label_35")
        self.B9_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_9.setGeometry(QtCore.QRect(120, 530, 81, 21))
        self.B9_CID_9.setObjectName("B9_CID_9")
        self.B10_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_15.setGeometry(QtCore.QRect(680, 500, 81, 21))
        self.B10_CID_15.setObjectName("B10_CID_15")
        self.B12_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_5.setGeometry(QtCore.QRect(1260, 560, 81, 21))
        self.B12_CID_5.setObjectName("B12_CID_5")
        self.B12_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_14.setGeometry(QtCore.QRect(1350, 500, 81, 21))
        self.B12_CID_14.setObjectName("B12_CID_14")
        self.B12_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_12.setGeometry(QtCore.QRect(1170, 500, 81, 21))
        self.B12_CID_12.setObjectName("B12_CID_12")
        self.B12_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_10.setGeometry(QtCore.QRect(1350, 530, 81, 21))
        self.B12_CID_10.setObjectName("B12_CID_10")
        self.B9_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_3.setGeometry(QtCore.QRect(300, 590, 81, 21))
        self.B9_CID_3.setObjectName("B9_CID_3")
        self.B11_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_13.setGeometry(QtCore.QRect(880, 500, 81, 21))
        self.B11_CID_13.setObjectName("B11_CID_13")
        self.B9_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_4.setGeometry(QtCore.QRect(30, 560, 81, 21))
        self.B9_CID_4.setObjectName("B9_CID_4")
        self.B12_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_8.setGeometry(QtCore.QRect(1170, 530, 81, 21))
        self.B12_CID_8.setObjectName("B12_CID_8")
        self.B10_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_0.setGeometry(QtCore.QRect(410, 590, 81, 21))
        self.B10_CID_0.setObjectName("B10_CID_0")
        self.B9_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_8.setGeometry(QtCore.QRect(30, 530, 81, 21))
        self.B9_CID_8.setObjectName("B9_CID_8")
        self.B9_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_11.setGeometry(QtCore.QRect(300, 530, 81, 21))
        self.B9_CID_11.setObjectName("B9_CID_11")
        self.B12_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_9.setGeometry(QtCore.QRect(1260, 530, 81, 21))
        self.B12_CID_9.setObjectName("B12_CID_9")
        self.B10_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B10_CID_13.setGeometry(QtCore.QRect(500, 500, 81, 21))
        self.B10_CID_13.setObjectName("B10_CID_13")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(770, 480, 71, 16))
        self.label_36.setObjectName("label_36")
        self.B12_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_13.setGeometry(QtCore.QRect(1260, 500, 81, 21))
        self.B12_CID_13.setObjectName("B12_CID_13")
        self.B12_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B12_CID_2.setGeometry(QtCore.QRect(1350, 590, 81, 21))
        self.B12_CID_2.setObjectName("B12_CID_2")
        self.B11_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_2.setGeometry(QtCore.QRect(970, 590, 81, 21))
        self.B11_CID_2.setObjectName("B11_CID_2")
        self.B9_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B9_CID_10.setGeometry(QtCore.QRect(210, 530, 81, 21))
        self.B9_CID_10.setObjectName("B9_CID_10")
        self.B11_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_7.setGeometry(QtCore.QRect(1060, 560, 81, 21))
        self.B11_CID_7.setObjectName("B11_CID_7")
        self.B11_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B11_CID_8.setGeometry(QtCore.QRect(790, 530, 81, 21))
        self.B11_CID_8.setObjectName("B11_CID_8")
        self.B15_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_6.setGeometry(QtCore.QRect(970, 690, 81, 21))
        self.B15_CID_6.setObjectName("B15_CID_6")
        self.B13_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_12.setGeometry(QtCore.QRect(30, 630, 81, 21))
        self.B13_CID_12.setText("")
        self.B13_CID_12.setObjectName("B13_CID_12")
        self.B15_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_15.setGeometry(QtCore.QRect(1060, 630, 81, 21))
        self.B15_CID_15.setObjectName("B15_CID_15")
        self.B15_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_4.setGeometry(QtCore.QRect(790, 690, 81, 21))
        self.B15_CID_4.setObjectName("B15_CID_4")
        self.B14_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_12.setGeometry(QtCore.QRect(410, 630, 81, 21))
        self.B14_CID_12.setObjectName("B14_CID_12")
        self.B14_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_11.setGeometry(QtCore.QRect(680, 660, 81, 21))
        self.B14_CID_11.setObjectName("B14_CID_11")
        self.B14_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_9.setGeometry(QtCore.QRect(500, 660, 81, 21))
        self.B14_CID_9.setObjectName("B14_CID_9")
        self.B14_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_14.setGeometry(QtCore.QRect(590, 630, 81, 21))
        self.B14_CID_14.setObjectName("B14_CID_14")
        self.B15_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_14.setGeometry(QtCore.QRect(970, 630, 81, 21))
        self.B15_CID_14.setObjectName("B15_CID_14")
        self.B13_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_7.setGeometry(QtCore.QRect(300, 690, 81, 21))
        self.B13_CID_7.setObjectName("B13_CID_7")
        self.B16_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_6.setGeometry(QtCore.QRect(1350, 690, 81, 21))
        self.B16_CID_6.setObjectName("B16_CID_6")
        self.B13_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_0.setGeometry(QtCore.QRect(30, 720, 81, 21))
        self.B13_CID_0.setObjectName("B13_CID_0")
        self.B16_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_1.setGeometry(QtCore.QRect(1260, 720, 81, 21))
        self.B16_CID_1.setObjectName("B16_CID_1")
        self.B16_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_4.setGeometry(QtCore.QRect(1170, 690, 81, 21))
        self.B16_CID_4.setObjectName("B16_CID_4")
        self.B15_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_11.setGeometry(QtCore.QRect(1060, 660, 81, 21))
        self.B15_CID_11.setObjectName("B15_CID_11")
        self.B13_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_1.setGeometry(QtCore.QRect(120, 720, 81, 21))
        self.B13_CID_1.setObjectName("B13_CID_1")
        self.B14_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_6.setGeometry(QtCore.QRect(590, 690, 81, 21))
        self.B14_CID_6.setObjectName("B14_CID_6")
        self.B14_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_4.setGeometry(QtCore.QRect(410, 690, 81, 21))
        self.B14_CID_4.setObjectName("B14_CID_4")
        self.B14_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_10.setGeometry(QtCore.QRect(590, 660, 81, 21))
        self.B14_CID_10.setObjectName("B14_CID_10")
        self.B13_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_5.setGeometry(QtCore.QRect(120, 690, 81, 21))
        self.B13_CID_5.setObjectName("B13_CID_5")
        self.B16_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_15.setGeometry(QtCore.QRect(1440, 630, 81, 21))
        self.B16_CID_15.setObjectName("B16_CID_15")
        self.B13_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_2.setGeometry(QtCore.QRect(210, 720, 81, 21))
        self.B13_CID_2.setObjectName("B13_CID_2")
        self.B14_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_3.setGeometry(QtCore.QRect(680, 720, 81, 21))
        self.B14_CID_3.setObjectName("B14_CID_3")
        self.B14_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_2.setGeometry(QtCore.QRect(590, 720, 81, 21))
        self.B14_CID_2.setObjectName("B14_CID_2")
        self.B16_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_0.setGeometry(QtCore.QRect(1170, 720, 81, 21))
        self.B16_CID_0.setObjectName("B16_CID_0")
        self.B15_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_9.setGeometry(QtCore.QRect(880, 660, 81, 21))
        self.B15_CID_9.setObjectName("B15_CID_9")
        self.B15_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_5.setGeometry(QtCore.QRect(880, 690, 81, 21))
        self.B15_CID_5.setObjectName("B15_CID_5")
        self.B16_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_7.setGeometry(QtCore.QRect(1440, 690, 81, 21))
        self.B16_CID_7.setObjectName("B16_CID_7")
        self.B15_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_1.setGeometry(QtCore.QRect(880, 720, 81, 21))
        self.B15_CID_1.setObjectName("B15_CID_1")
        self.B15_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_12.setGeometry(QtCore.QRect(790, 630, 81, 21))
        self.B15_CID_12.setText("")
        self.B15_CID_12.setObjectName("B15_CID_12")
        self.B13_CID_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_6.setGeometry(QtCore.QRect(210, 690, 81, 21))
        self.B13_CID_6.setObjectName("B13_CID_6")
        self.B15_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_3.setGeometry(QtCore.QRect(1060, 720, 81, 21))
        self.B15_CID_3.setObjectName("B15_CID_3")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(10, 610, 71, 16))
        self.label_37.setObjectName("label_37")
        self.B15_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_0.setGeometry(QtCore.QRect(790, 720, 81, 21))
        self.B15_CID_0.setObjectName("B15_CID_0")
        self.B16_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_3.setGeometry(QtCore.QRect(1440, 720, 81, 21))
        self.B16_CID_3.setObjectName("B16_CID_3")
        self.B14_CID_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_1.setGeometry(QtCore.QRect(500, 720, 81, 21))
        self.B14_CID_1.setObjectName("B14_CID_1")
        self.B15_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_10.setGeometry(QtCore.QRect(970, 660, 81, 21))
        self.B15_CID_10.setObjectName("B15_CID_10")
        self.B13_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_14.setGeometry(QtCore.QRect(210, 630, 81, 21))
        self.B13_CID_14.setObjectName("B13_CID_14")
        self.B14_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_5.setGeometry(QtCore.QRect(500, 690, 81, 21))
        self.B14_CID_5.setObjectName("B14_CID_5")
        self.B16_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_11.setGeometry(QtCore.QRect(1440, 660, 81, 21))
        self.B16_CID_11.setObjectName("B16_CID_11")
        self.B14_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_8.setGeometry(QtCore.QRect(410, 660, 81, 21))
        self.B14_CID_8.setObjectName("B14_CID_8")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(390, 610, 71, 16))
        self.label_38.setObjectName("label_38")
        self.B14_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_7.setGeometry(QtCore.QRect(680, 690, 81, 21))
        self.B14_CID_7.setObjectName("B14_CID_7")
        self.B13_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_13.setGeometry(QtCore.QRect(120, 630, 81, 21))
        self.B13_CID_13.setObjectName("B13_CID_13")
        self.B13_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_15.setGeometry(QtCore.QRect(300, 630, 81, 21))
        self.B13_CID_15.setObjectName("B13_CID_15")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(1150, 610, 71, 16))
        self.label_39.setObjectName("label_39")
        self.B13_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_9.setGeometry(QtCore.QRect(120, 660, 81, 21))
        self.B13_CID_9.setObjectName("B13_CID_9")
        self.B14_CID_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_15.setGeometry(QtCore.QRect(680, 630, 81, 21))
        self.B14_CID_15.setObjectName("B14_CID_15")
        self.B16_CID_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_5.setGeometry(QtCore.QRect(1260, 690, 81, 21))
        self.B16_CID_5.setObjectName("B16_CID_5")
        self.B16_CID_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_14.setGeometry(QtCore.QRect(1350, 630, 81, 21))
        self.B16_CID_14.setObjectName("B16_CID_14")
        self.B16_CID_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_12.setGeometry(QtCore.QRect(1170, 630, 81, 21))
        self.B16_CID_12.setObjectName("B16_CID_12")
        self.B16_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_10.setGeometry(QtCore.QRect(1350, 660, 81, 21))
        self.B16_CID_10.setObjectName("B16_CID_10")
        self.B13_CID_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_3.setGeometry(QtCore.QRect(300, 720, 81, 21))
        self.B13_CID_3.setObjectName("B13_CID_3")
        self.B15_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_13.setGeometry(QtCore.QRect(880, 630, 81, 21))
        self.B15_CID_13.setObjectName("B15_CID_13")
        self.B13_CID_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_4.setGeometry(QtCore.QRect(30, 690, 81, 21))
        self.B13_CID_4.setObjectName("B13_CID_4")
        self.B16_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_8.setGeometry(QtCore.QRect(1170, 660, 81, 21))
        self.B16_CID_8.setObjectName("B16_CID_8")
        self.B14_CID_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_0.setGeometry(QtCore.QRect(410, 720, 81, 21))
        self.B14_CID_0.setObjectName("B14_CID_0")
        self.B13_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_8.setGeometry(QtCore.QRect(30, 660, 81, 21))
        self.B13_CID_8.setObjectName("B13_CID_8")
        self.B13_CID_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_11.setGeometry(QtCore.QRect(300, 660, 81, 21))
        self.B13_CID_11.setObjectName("B13_CID_11")
        self.B16_CID_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_9.setGeometry(QtCore.QRect(1260, 660, 81, 21))
        self.B16_CID_9.setObjectName("B16_CID_9")
        self.B14_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B14_CID_13.setGeometry(QtCore.QRect(500, 630, 81, 21))
        self.B14_CID_13.setObjectName("B14_CID_13")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(770, 610, 71, 16))
        self.label_40.setObjectName("label_40")
        self.B16_CID_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_13.setGeometry(QtCore.QRect(1260, 630, 81, 21))
        self.B16_CID_13.setObjectName("B16_CID_13")
        self.B16_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B16_CID_2.setGeometry(QtCore.QRect(1350, 720, 81, 21))
        self.B16_CID_2.setObjectName("B16_CID_2")
        self.B15_CID_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_2.setGeometry(QtCore.QRect(970, 720, 81, 21))
        self.B15_CID_2.setObjectName("B15_CID_2")
        self.B13_CID_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.B13_CID_10.setGeometry(QtCore.QRect(210, 660, 81, 21))
        self.B13_CID_10.setObjectName("B13_CID_10")
        self.B15_CID_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_7.setGeometry(QtCore.QRect(1060, 690, 81, 21))
        self.B15_CID_7.setObjectName("B15_CID_7")
        self.B15_CID_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.B15_CID_8.setGeometry(QtCore.QRect(790, 660, 81, 21))
        self.B15_CID_8.setObjectName("B15_CID_8")
        self.outputpath = QtWidgets.QTextEdit(self.centralwidget)
        self.outputpath.setGeometry(QtCore.QRect(130, 140, 151, 51))
        self.outputpath.setObjectName("outputpath")
        default_path = os.path.join(os.getcwd(), "") # 設定預設路徑為當前工作目錄
        self.outputpath.setText(default_path)

        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(130, 120, 101, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(130, 20, 151, 16))
        self.label_42.setObjectName("label_42")
        self.MTB_SETTING_filepath = QtWidgets.QLineEdit(self.centralwidget)
        self.MTB_SETTING_filepath.setGeometry(QtCore.QRect(130, 40, 141, 21))
        self.MTB_SETTING_filepath.setText("")
        self.MTB_SETTING_filepath.setObjectName("MTB_SETTING_filepath")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(130, 70, 151, 16))
        self.label_43.setObjectName("label_43")
        self.azimuth_angle = QtWidgets.QLineEdit(self.centralwidget)
        self.azimuth_angle.setGeometry(QtCore.QRect(130, 90, 51, 21))
        self.azimuth_angle.setObjectName("azimuth_angle")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(190, 70, 61, 16))
        self.label_44.setObjectName("label_44")
        self.elevation_angle = QtWidgets.QLineEdit(self.centralwidget)
        self.elevation_angle.setGeometry(QtCore.QRect(190, 90, 51, 21))
        self.elevation_angle.setObjectName("elevation_angle")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1250, 70, 211, 71))
        self.pushButton.setObjectName("pushButton")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(10, 750, 60, 16))
        self.label_45.setObjectName("label_45")
        self.command = QtWidgets.QTextEdit(self.centralwidget)
        self.command.setGeometry(QtCore.QRect(30, 770, 541, 121))
        self.command.setObjectName("command")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 24))
        self.menubar.setObjectName("menubar")
        self.menuBuildRunDescription = QtWidgets.QMenu(self.menubar)
        self.menuBuildRunDescription.setObjectName("menuBuildRunDescription")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuBuildRunDescription.menuAction())

        self.retranslateUi(MainWindow)

        # 按下按鈕->執行 build_description 函數
        self.pushButton.clicked.connect(self.build_description)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RunName"))
        self.label_2.setText(_translate("MainWindow", "StartDate"))
        self.label_3.setText(_translate("MainWindow", "EndDate"))
        self.label_4.setText(_translate("MainWindow", "FPGA SN"))
        self.label_5.setText(_translate("MainWindow", "MTB SN"))
        self.label_6.setText(_translate("MainWindow", "Board 01"))
        self.label_7.setText(_translate("MainWindow", "Board 02"))
        self.label_8.setText(_translate("MainWindow", "Board 04"))
        self.label_9.setText(_translate("MainWindow", "Board 03"))
        self.label_10.setText(_translate("MainWindow", "Board 05"))
        self.label_11.setText(_translate("MainWindow", "Board 06"))
        self.label_12.setText(_translate("MainWindow", "Board 07"))
        self.label_13.setText(_translate("MainWindow", "Board 08"))
        self.label_14.setText(_translate("MainWindow", "MTB SN"))
        self.label_15.setText(_translate("MainWindow", "Board 13"))
        self.label_16.setText(_translate("MainWindow", "Board 11"))
        self.label_17.setText(_translate("MainWindow", "Board 10"))
        self.label_18.setText(_translate("MainWindow", "FPGA SN"))
        self.label_19.setText(_translate("MainWindow", "Board 15"))
        self.label_20.setText(_translate("MainWindow", "Board 12"))
        self.label_21.setText(_translate("MainWindow", "Board 14"))
        self.label_22.setText(_translate("MainWindow", "Board 16"))
        self.label_23.setText(_translate("MainWindow", "Board 09"))
        self.label_24.setText(_translate("MainWindow", "Channel ID"))
        self.label_25.setText(_translate("MainWindow", "B1"))
        self.label_26.setText(_translate("MainWindow", "B2"))
        self.label_27.setText(_translate("MainWindow", "B4"))
        self.label_29.setText(_translate("MainWindow", "B3"))
        self.label_28.setText(_translate("MainWindow", "B6"))
        self.label_30.setText(_translate("MainWindow", "B7"))
        self.label_31.setText(_translate("MainWindow", "B5"))
        self.label_32.setText(_translate("MainWindow", "B8"))
        self.label_33.setText(_translate("MainWindow", "B9"))
        self.label_34.setText(_translate("MainWindow", "B10"))
        self.label_35.setText(_translate("MainWindow", "B12"))
        self.label_36.setText(_translate("MainWindow", "B11"))
        self.label_37.setText(_translate("MainWindow", "B13"))
        self.label_38.setText(_translate("MainWindow", "B14"))
        self.label_39.setText(_translate("MainWindow", "B16"))
        self.label_40.setText(_translate("MainWindow", "B15"))
        self.label_41.setText(_translate("MainWindow", "Output File Path"))
        self.label_42.setText(_translate("MainWindow", "MTB_SETTING(.txt file)"))
        self.label_43.setText(_translate("MainWindow", "方位角"))
        self.label_44.setText(_translate("MainWindow", "仰角"))
        self.pushButton.setText(_translate("MainWindow", "Build Run Description!"))
        self.label_45.setText(_translate("MainWindow", "備註"))
        self.menuBuildRunDescription.setTitle(_translate("MainWindow", "BuildRunDescription"))
    
    def get_input_values(self):
        input_values = {
            "run_name": self.RunName_input.text(),
            "start_date": self.StartDate_input.text(),
            "end_date": self.EndDate_input.text(),
            "MTB_SETTING_filepath": self.MTB_SETTING_filepath.text(),
            "azimuth_angle": self.azimuth_angle.text(),
            "elevation_angle": self.elevation_angle.text(),
            "outputpath": self.outputpath.toPlainText(),
            "command": self.command.toPlainText(),
        }
        fpga_sn = {}
        mtb_sn = {}
        for i in range(1, 17):
            board_num = f"{i:02d}"
            fpga_attr = f"FPGASN_ipt_{board_num}"
            mtb_attr = f"MTBSN_ipt_{board_num}"
            board_key = f"B{i}"
            
            if hasattr(self, fpga_attr):
                fpga_sn[board_key] = getattr(self, fpga_attr).text()
            
            if hasattr(self, mtb_attr):
                mtb_sn[board_key] = getattr(self, mtb_attr).text()
        
        input_values["fpga_sn"] = fpga_sn
        input_values["mtb_sn"] = mtb_sn

        def get_cid_list(board_idx):
            cid_list = []
            for cid_idx in range(16): 
                attr_name = f"B{board_idx}_CID_{cid_idx}"

                if hasattr(self, attr_name): 
                    cid_list.append(getattr(self, attr_name).text())
                else:
                    cid_list.append('X') 
            return cid_list

        for i in range(1, 17): 
            board_key = f"B{i}_scintillator_sn"
            input_values[board_key] = get_cid_list(i)

        return input_values
    
    def build_description(self):
        """
        當按鈕被點擊時，此函數將會執行。
        檢查輸出路徑是否已存在檔案，並彈出警告視窗詢問是否覆蓋。
        """
        print("Build Run Description 按鈕被點擊！開始執行描述文件建立。")
        values = self.get_input_values()
    
        run_name = values["run_name"].strip()
        output_base_path = values["outputpath"].strip()
        
        if not run_name:
             run_name = 'default_run'
        
        if not output_base_path:
            output_filename = f"{run_name}_description.json"
            output_path = output_filename
        else:
            output_filename = f"{run_name}_description.json"
            output_path = os.path.join(output_base_path, output_filename)
        
        if os.path.exists(output_path):
            
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setWindowTitle("確認覆蓋檔案?")
            msg.setText(f"檔案已存在:\n{output_path}\n\n 確定要覆蓋它嗎？")
            
            # 設定按鈕：Yes (覆蓋) 和 No (取消並回到主頁)
            msg.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
            
            returnValue = msg.exec_()
            
            if returnValue == QtWidgets.QMessageBox.No:
                print("操作取消。回到主頁面。")
                return 

        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(values, f, indent=4, ensure_ascii=False)
            
            print(f"描述文件已成功儲存至: {output_path}")
            
        except Exception as e:
            print(f"儲存 JSON 文件時發生錯誤: {e}")
            print(f"檢查 Output File Path 是否為有效的目錄路徑：{output_base_path}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
